#!/usr/bin/env python3
"""Generate Godot resources and registration for the Airwindohhs catalog."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
from dataclasses import asdict, dataclass
from pathlib import Path

GENERATOR_VERSION = "1.0.0"
MAX_PARAMETERS = 16

CLASS_RE = re.compile(
    r"namespace\s+airwindohhs::(\w+).*?"
    r"template\s*<\s*typename\s+\w+\s*>\s*"
    r"class\s+(\w+)\s+final\s*:\s*public\s+Effect<\w+>",
    re.DOTALL,
)
PARAM_COUNT_RE = re.compile(r"kNumParameters\s*=\s*(\d+)")
PARAMETER_NAMES_RE = re.compile(
    r"get_parameter_name\(int index\).*?\{(.*?)"
    r"constexpr\s+std::string_view\s+get_parameter_title",
    re.DOTALL,
)
CASE_NAME_RE = re.compile(r'case\s+kParam\w+\s*:\s*return\s+"([^"]*)"')


def slug(value: str) -> str:
    result = re.sub(r"[^a-z0-9]+", "_", value.lower()).strip("_")
    return result or "parameter"


def camel(value: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in re.split(r"[^A-Za-z0-9]+", value) if part)


def cpp_float(value: float) -> str:
    text = f"{value:.9g}"
    if "." not in text and "e" not in text.lower():
        text += ".0"
    return text + "f"


@dataclass(frozen=True)
class Effect:
    effect_id: str
    category: str
    namespace: str
    cpp_class: str
    godot_class: str
    header: str
    parameter_count: int
    parameter_ids: tuple[str, ...]
    parameter_ranges: tuple[tuple[float, float], ...]


def _git(repo: Path, *args: str) -> str:
    return subprocess.check_output(["git", "-C", str(repo), *args], text=True).strip()


def _parameter_ids(source: str, effect_id: str, count: int) -> tuple[str, ...]:
    match = PARAMETER_NAMES_RE.search(source)
    names = CASE_NAME_RE.findall(match.group(1)) if match else []
    if len(names) != count:
        raise ValueError(f"{effect_id}: expected {count} parameter names, parsed {len(names)}")
    seen: dict[str, int] = {}
    result = []
    for index, name in enumerate(names):
        base = slug(name) or f"parameter_{index}"
        occurrence = seen.get(base, 0)
        seen[base] = occurrence + 1
        unique = base if occurrence == 0 else f"{base}_{occurrence + 1}"
        result.append(f"airwindohhs.{effect_id}.{unique}")
    return tuple(result)


def scan_catalog(airwindohhs: Path, exclusions_path: Path | None = None,
                 overrides_path: Path | None = None) -> list[Effect]:
    include = airwindohhs / "include"
    exclusions = set()
    if exclusions_path and exclusions_path.exists():
        document = json.loads(exclusions_path.read_text(encoding="utf-8"))
        exclusions = {entry["effect_id"] for entry in document.get("effects", [])}
    if overrides_path is None:
        overrides_path = Path(__file__).resolve().parents[1] / "config" / "parameter_overrides.json"
    overrides_document = json.loads(overrides_path.read_text(encoding="utf-8"))
    overrides = {
        (entry["effect_id"], entry["parameter_index"]):
            (float(entry["minimum"]), float(entry["maximum"]))
        for entry in overrides_document.get("parameters", [])
    }

    effects = []
    for header in sorted(include.glob("*/*.hpp")):
        source = header.read_text(encoding="utf-8")
        class_match = CLASS_RE.search(source)
        count_match = PARAM_COUNT_RE.search(source)
        if not class_match or not count_match:
            raise ValueError(f"could not parse generated effect header: {header}")
        namespace, cpp_class = class_match.groups()
        category = header.parent.name
        effect_id = f"{slug(category)}.{slug(header.stem)}"
        if effect_id in exclusions:
            continue
        parameter_count = int(count_match.group(1))
        if parameter_count > MAX_PARAMETERS:
            raise ValueError(f"{effect_id}: {parameter_count} parameters exceeds {MAX_PARAMETERS}")
        effects.append(
            Effect(
                effect_id=effect_id,
                category=category,
                namespace=namespace,
                cpp_class=cpp_class,
                godot_class=f"Airwindohhs{camel(category)}{camel(cpp_class)}",
                header=header.relative_to(include).as_posix(),
                parameter_count=parameter_count,
                parameter_ids=_parameter_ids(source, effect_id, parameter_count),
                parameter_ranges=tuple(
                    overrides.get((effect_id, index), (0.0, 1.0))
                    for index in range(parameter_count)
                ),
            )
        )
    classes = [effect.godot_class for effect in effects]
    if len(classes) != len(set(classes)):
        raise ValueError("generated Godot class names are not unique")
    return effects


def _declarations(effects: list[Effect]) -> str:
    lines = [
        "// Generated by tools/generate_catalog.py. Do not edit.",
        "#pragma once",
        "#include <airwindohhs_godot/audio_effect.hpp>",
        "",
        "namespace airwindohhs_godot {",
    ]
    for effect in effects:
        lines.extend(
            [
                f"class {effect.godot_class} final : public AirwindohhsAudioEffect {{",
                f"    GDCLASS({effect.godot_class}, AirwindohhsAudioEffect)",
                "",
                "public:",
                f"    {effect.godot_class}();",
                "",
                "protected:",
                "    static void _bind_methods() {}",
                "};",
                "",
            ]
        )
    lines.extend(["void register_generated_effects();", "", "} // namespace airwindohhs_godot", ""])
    return "\n".join(lines)


def _shard_source(index: int, effects: list[Effect]) -> str:
    lines = [
        "// Generated by tools/generate_catalog.py. Do not edit.",
        '#include "effects.hpp"',
    ]
    lines.extend(f'#include <{effect.header}>' for effect in effects)
    lines.extend(["", "namespace airwindohhs_godot {", ""])
    for effect in effects:
        qualified = f"airwindohhs::{effect.namespace}::{effect.cpp_class}<float>"
        metadata = f"airwindohhs::{effect.namespace}"
        lines.extend(
            [
                f"{effect.godot_class}::{effect.godot_class}() {{",
                f'    configure<{qualified}>("{effect.effect_id}", "{effect.category}",',
                f"        {metadata}::k_name, {metadata}::k_short_description, {metadata}::k_tags);",
            ]
        )
        for parameter_index, (minimum, maximum) in enumerate(effect.parameter_ranges):
            if minimum != 0.0 or maximum != 1.0:
                lines.append(
                    f"    set_parameter_range({parameter_index}, {cpp_float(minimum)}, {cpp_float(maximum)});")
        lines.append("}")
        lines.append("")
    lines.extend([f"void register_generated_effects_{index:02d}() {{"])
    lines.extend(f"    GDREGISTER_CLASS({effect.godot_class});" for effect in effects)
    lines.extend(["}", "", "} // namespace airwindohhs_godot", ""])
    return "\n".join(lines)


def _registration(shard_count: int) -> str:
    lines = [
        "// Generated by tools/generate_catalog.py. Do not edit.",
        '#include "effects.hpp"',
        "",
        "namespace airwindohhs_godot {",
    ]
    lines.extend(f"void register_generated_effects_{index:02d}();" for index in range(shard_count))
    lines.extend(["", "void register_generated_effects() {"])
    lines.extend(f"    register_generated_effects_{index:02d}();" for index in range(shard_count))
    lines.extend(["}", "", "} // namespace airwindohhs_godot", ""])
    return "\n".join(lines)


def _validation_shard(index: int, effects: list[Effect]) -> str:
    lines = [
        "// Generated by tools/generate_catalog.py. Do not edit.",
        '#include "catalog_validation.hpp"',
    ]
    lines.extend(f'#include <{effect.header}>' for effect in effects)
    lines.extend(["", "namespace airwindohhs_godot::validation {", "",
                  f"void validate_catalog_{index:02d}(Report& report) {{"])
    for effect in effects:
        qualified = f"airwindohhs::{effect.namespace}::{effect.cpp_class}<float>"
        overrides = [
            (parameter_index, minimum, maximum)
            for parameter_index, (minimum, maximum) in enumerate(effect.parameter_ranges)
            if minimum != 0.0 or maximum != 1.0
        ]
        ranges = ", ".join(
            f"ParameterRange{{{index}, {cpp_float(minimum)}, {cpp_float(maximum)}}}"
            for index, minimum, maximum in overrides
        )
        lines.append(
            f'    validate_effect<{qualified}>("{effect.effect_id}", report, {{{ranges}}});')
    lines.extend(["}", "", "} // namespace airwindohhs_godot::validation", ""])
    return "\n".join(lines)


def generate_catalog(airwindohhs: Path, output: Path, shard_count: int = 16,
                     exclusions_path: Path | None = None,
                     overrides_path: Path | None = None) -> None:
    output.mkdir(parents=True, exist_ok=True)
    if exclusions_path is None:
        exclusions_path = Path(__file__).resolve().parents[1] / "config" / "exclusions.json"
    if overrides_path is None:
        overrides_path = Path(__file__).resolve().parents[1] / "config" / "parameter_overrides.json"
    effects = scan_catalog(airwindohhs, exclusions_path, overrides_path)
    exclusion_document = json.loads(exclusions_path.read_text(encoding="utf-8"))
    overrides_document = json.loads(overrides_path.read_text(encoding="utf-8"))
    shards = [[] for _ in range(shard_count)]
    for index, effect in enumerate(effects):
        shards[index % shard_count].append(effect)

    (output / "effects.hpp").write_text(_declarations(effects), encoding="utf-8")
    shard_files = []
    validation_files = []
    for index, shard in enumerate(shards):
        filename = f"effects_{index:02d}.cpp"
        shard_files.append(filename)
        (output / filename).write_text(_shard_source(index, shard), encoding="utf-8")
        validation_filename = f"validation_{index:02d}.cpp"
        validation_files.append(validation_filename)
        (output / validation_filename).write_text(
            _validation_shard(index, shard), encoding="utf-8")
    (output / "register_effects.cpp").write_text(_registration(shard_count), encoding="utf-8")
    sources = ["${CMAKE_CURRENT_SOURCE_DIR}/generated/register_effects.cpp"] + [
        f"${{CMAKE_CURRENT_SOURCE_DIR}}/generated/{filename}" for filename in shard_files
    ]
    (output / "sources.cmake").write_text(
        "# Generated by tools/generate_catalog.py. Do not edit.\n"
        "set(AIRWINDOHHS_GODOT_GENERATED_SOURCES\n    " + "\n    ".join(sources) + "\n)\n",
        encoding="utf-8",
    )
    validation_sources = [
        f"${{CMAKE_CURRENT_SOURCE_DIR}}/generated/{filename}" for filename in validation_files
    ]
    (output / "validation_sources.cmake").write_text(
        "# Generated by tools/generate_catalog.py. Do not edit.\n"
        "set(AIRWINDOHHS_GODOT_VALIDATION_SOURCES\n    " +
        "\n    ".join(validation_sources) + "\n)\n",
        encoding="utf-8",
    )

    airwindows_version = (airwindohhs / "airwindows-version.txt").read_text(encoding="utf-8").strip()
    manifest = {
        "schema_version": 1,
        "generator_version": GENERATOR_VERSION,
        "source": "https://github.com/jinpavg/airwindohhs.git",
        "upstream": "https://github.com/isabelgk/airwindohhs.git",
        "source_policy": "latest-default-branch",
        "resolved_airwindohhs_commit": _git(airwindohhs, "rev-parse", "HEAD"),
        "resolved_airwindows_source": airwindows_version,
        "license": "MIT",
        "compatible_effect_count": len(effects),
        "excluded_effect_count": len(exclusion_document.get("effects", [])),
        "exclusions": exclusion_document.get("effects", []),
        "parameter_overrides": overrides_document.get("parameters", []),
        "shards": shard_files,
        "validation_shards": validation_files,
        "effects": [asdict(effect) for effect in effects],
    }
    (output / "catalog.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--airwindohhs", type=Path, required=True)
    parser.add_argument("--output", type=Path, default=Path("generated"))
    parser.add_argument("--exclusions", type=Path, default=Path("config/exclusions.json"))
    parser.add_argument("--parameter-overrides", type=Path,
                        default=Path("config/parameter_overrides.json"))
    parser.add_argument("--shards", type=int, default=16)
    args = parser.parse_args()
    generate_catalog(args.airwindohhs.resolve(), args.output.resolve(), args.shards,
                     args.exclusions.resolve(), args.parameter_overrides.resolve())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
